title: Sreelekha Renjith 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Data Analyst
  <br><br>
  Sydney, NSW
  <br><br>
  <a href="https://www.linkedin.com/in/sreelekha-renjith-b175a0139/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

